version: '3.5'

services:
  dashboard:
    build: ./dashboard/
    container_name: dashboard
    environment:
      - PORT=3000
    restart: always
    depends_on:
      - mongo
    ports:
      - "8080:3000"
    environment:
        - MONGODB=mongodb://mongo:27017

  mongo:
    image: "mongo"
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    restart: always